### ISSUE TITLE
Trouble Installing PolyHaven Plugin for Maya

### ISSUE THREAD

**Issue by RaphaelRoman** [OmidGhotbi/polyhavenassets#1]
Hello. I was looking at your PolyHaven plugin for Maya on GitHub. Following the installation, I got everything set up as easily as it was written, but I got a couple of errors when clicking the shelf tool. First, I had errors for PySide2 and shiboken2 not being found. I just changed them in your files to PySide6 and shiboken6. I thought it would be fine afterwards, but I'm now getting this error: 

# Error: PermissionError: file E:\03 Creative/Animation/DCC/Maya/Plugins/PolyHaven\get_path.py line 35: [Errno 13] Permission denied: 'settings.json'

I already made sure the directory was fully accessible, so I'm unsure what to do at this point. My other assumption is that perhaps I just need to work in an earlier version of Maya. I usually work in 2023, but I'm trying out 2025. Do you have any suggestions? 

Update: I tried installing it in Maya 2023, reverted the PySide and shiboken imports. I'm stilling getting the same error as above.

**Comment by OmidGhotbi** [comment]
which setup steps did you follow and did you just try to run Maya as administrator?
the best way and easiest is just to:
1- Unzip the Download release in C:\ for Windows user or ~/ for Mac or Linux user. The final path will be like this C:\PolyHave
2- Drag and drop shelf.py into Maya viewport, now you have Polyhaven shelf in Maya,

**Comment by RaphaelRoman** [comment]
I actually made a mistake on the final path. I corrected that, but I'm still having the same error now that I'm in C:/PolyHaven. I re-ran the setup.bat as well just in case. Not sure what to do from here.

**Comment by OmidGhotbi** [comment]
i'm pretty sure you are making a small mistake, I tested on Maya 2024 and it works without any issues.
![image](https://github.com/user-attachments/assets/1c33b644-7f6a-45e2-a423-e24f569b37c9)

**Comment by OmidGhotbi** [comment]
maybe you have a firewall or something blocking the access ? did you try to run Maya as administrator?

**Comment by RaphaelRoman** [comment]
Hey! Sorry about the late reply. I've been quite busy and got sick recently. I just switched Maya to run as administrator and got it working fine. Thank you for the help!

**Comment by OmidGhotbi** [comment]
oh great to hear it's working, i believe you need to run it just one time as administrator then should be fine.
by the way, i just double-checked it and I think the right-click download button did not work use another download button I will fix right click later. use right-click on items to assign them to an object or add/create new objects.

**Comment by RaphaelRoman** [comment]
Ah I see. Got it. Glad we were able to find something out of this. Thanks again!

**Comment by RaphaelRoman** [comment]
Hey I actually just tried turning off running Maya as admin and it won't work unless I run it as admin. Just to let you know.

**Comment by OmidGhotbi** [comment]
it may be some change in Maya mine works perfectly I will test it on another PC and see if I need to do any code change. thank you for reporting that.
